---
- name: Set up a fresh machine
  hosts: localhost
  become: yes
  tasks:
    - name: Install yay (Yet Another Yaourt)
      ansible.builtin.pacman:
        name: yay
        state: present

    - name: Install Obsidian
      ansible.builtin.aur:
        name: obsidian-bin
        state: present

    - name: Ignore power key
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#HandlePowerKey=poweroff"
        line: "HandlePowerKey=ignore"

    - name: Update GRUB for non-NVIDIA GPU
      ansible.builtin.command: |
        sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=""/' /etc/default/grub && sudo grub-mkconfig -o /boot/grub/grub.cfg
      when: ansible_facts['devices']['gpus'] is not defined or 'nvidia' not in ansible_facts['devices']['gpus']

    - name: Update GRUB for NVIDIA GPU
      ansible.builtin.command: |
        sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="nvidia_drm.modeset=1"/' /etc/default/grub && sudo grub-mkconfig -o /boot/grub/grub.cfg
      when: ansible_facts['devices']['gpus'] is defined and 'nvidia' in ansible_facts['devices']['gpus']

    - name: Install flatpak and WebCord
      ansible.builtin.command: yay -S flatpak --noconfirm && flatpak install io.github.spacingbat3.webcord

    - name: Replace Visual Studio Code with visual-studio-code-bin and install Whatsie
      ansible.builtin.command: yay -R code && yay -S visual-studio-code-bin --noconfirm

    - name: Install additional packages
      ansible.builtin.command: yay -S hyde-cli-git qrencode gnome-clocks tree noto-fonts-emoji wget chromium cava btop neofetch ani-cli mov-cli neovim kitty ranger encryptpad rclone rclone-browser pavucontrol zathura zathura-pdf-mupdf ranger nautilus --noconfirm

    - name: Install Neovim, Tmux, and related packages
      ansible.builtin.command: yay -S tmux ripgrep ttf-fira-code ttf-firacode-nerd luarocks nodejs npm pnpm --noconfirm && sudo luarocks install persistence.nvim && npm install -g eslint @biomejs/biome

    - name: Install SDDM astronaut theme
      ansible.builtin.command: |
        sudo git clone https://github.com/keyitdev/sddm-astronaut-theme.git /usr/share/sddm/themes/sddm-astronaut-theme &&
        sudo cp /usr/share/sddm/themes/sddm-astronaut-theme/Fonts/* /usr/share/fonts/ &&
        echo "[Theme]\nCurrent=sddm-astronaut-theme" | sudo tee /etc/sddm.conf

    - name: Open LINE Chrome extension page
      ansible.builtin.command: chromium https://chromewebstore.google.com/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc?hl=en

    - name: Create line.desktop file for LINE application
      ansible.builtin.file:
        path: ~/.local/share/applications
        state: directory

    - name: Write LINE desktop entry
      ansible.builtin.copy:
        dest: ~/.local/share/applications/line.desktop
        content: |
          [Desktop Entry]
          Version=1.0
          Name=LINE
          Comment=Line Messanger application
          Exec=chromium --app=chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html
          Icon=/home/faz/.config/chromium/Default/Extensions/ophjlpahpchlmihnnnihgmmeilfjmjjc/3.3.0_0/line_logo_128x128_on.png
          Terminal=false
          Type=Application

    - name: Install JDK, MultiMC and Whatsie
      ansible.builtin.command: yay -S jdk21-openjdk multimc-bin --noconfirm

    - name: Install Spotify and Spicetify
      ansible.builtin.command: yay -S spotify spicetify-cli --noconfirm && sudo chmod a+wr /opt/spotify && sudo chmod a+wr /opt/spotify/Apps -R

    - name: Install Python, pix2tex and Tesseract
      ansible.builtin.command: yay -S python-pip && sudo rm /usr/lib/python3.12/EXTERNALLY-MANAGED && pip install pix2tex && yay -S tesseract tesseract-eng-data tesseract-data-jpn --noconfirm

    - name: Install development tools
      ansible.builtin.command: yay -S intellij-idea-community-edition intellij-idea-ultimate-edition pycharm-community-edition pycharm-professional android-studio virtualbox virtualbox-host-modules-arch qbittorrent-git ventoy-bin --noconfirm && sudo /sbin/vboxreload

    - name: Set up SSH and UFW
      ansible.builtin.command: |
        sudo pacman -S ufw openssh --noconfirm &&
        sudo sed -i 's/#Port 22/Port 6519/g' /etc/ssh/sshd_config &&
        sudo ufw allow 6519 &&
        sudo ufw enable &&
        sudo ufw status numbered &&
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config &&
        sudo systemctl enable sshd &&
        sudo systemctl start sshd &&
        sudo systemctl status sshd &&
        sudo pacman -S libpam-google-authenticator --noconfirm &&
        google-authenticator &&
        sudo systemctl restart sshd &&
        curl http://ifconfig.me
